### ISSUE TITLE
Match Drinks to movies

### ISSUE THREAD

**Issue by micahlanham** [micahlanham/Moving-picture-potions#7]

**Comment by Javamang21** [comment]
## Movies and Drinks
## Cocktail Db API

- Action/Adventure/Sport : Tequila 

- Biography/ History/ Western/ War : Scotch or Bourbon, Beer

- Crime /Documentary/ Drama/ Film Noir/ Mystery/ Romance : Gin, Wine

- Animation/ Family/ Music/ Musical/Comedy: Rum

- Fantasy/ Sci-fi/Thriller/ Horror/:  Vodka, Rum
